[1,"Error occurred during cleanup: Error: プロセスはファイルにアクセスできません。別のプロセスが使用中です。 (os error 32): remove 'C:\\Users\\Tthre\\AppData\\Local\\Temp\\quarto-session56b56ccad34ed244'\n"]
